// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR8pMP_j20j-3V8vFmfh0cgtZuZPGYBHA',
    appId: '1:1041049357972:web:494a392baec8ac9e04ee81',
    messagingSenderId: '1041049357972',
    projectId: 'whatsapp-backend-635e3',
    authDomain: 'whatsapp-backend-635e3.firebaseapp.com',
    storageBucket: 'whatsapp-backend-635e3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTHg4zlZbfyxfO_zJdFtitZTEOsKS9vV0',
    appId: '1:1041049357972:android:d75083858f62dd6204ee81',
    messagingSenderId: '1041049357972',
    projectId: 'whatsapp-backend-635e3',
    storageBucket: 'whatsapp-backend-635e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEkOVeeG5eEWdYylYHuYoESANfAa1DU_Q',
    appId: '1:1041049357972:ios:458f1e11bde76d6d04ee81',
    messagingSenderId: '1041049357972',
    projectId: 'whatsapp-backend-635e3',
    storageBucket: 'whatsapp-backend-635e3.firebasestorage.app',
    iosBundleId: 'com.example.iaProject',
  );
}
